apiVersion: apps/v1
kind: Deployment
metadata:
  name: niontive-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: h22wiapcr.azurecr.io/hello-world:v1